const GRUPPE5 = [
    {
        nr: 1,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -16.20896, 
        lng: -48.00766,
    },
    {
        nr: 2,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -16.00896, 
        lng: -48.10766,
    },
    {
        nr: 3,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -16.10896, 
        lng: -48.00766,
    },
    {
        nr: 4,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -16.10896, 
        lng: -48.10766,
    },
    {
        nr: 5,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -16.00896, 
        lng: -48.00766,
    },

];