const GRUPPE5 = [
    {
        nr: 1,
        user: "Bus Stop W3",
        intro: "Long waiting times",
        about: " People waiting at a busy bus stop during rush hour on the W3. People who take the bus often say that they have to wait for a long time and don´t always get on their bus on the first try because it is already to full when it arrives at the bus stop. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='bus_stop_W3_g5.jpg' />", 
        lat:  -15.785188, 
        lng: -47.887890,
    },
    {
        nr: 2,
        user: "Trafic in Brasilia",
        intro: "Lanes, lanes, lanes...",
        about: "Even the massive 6 lane highway cannot cope with the number of cars on the streets of the capital. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='traffic_g5.jpg'>", 
        lat:  -15.793870, 
        lng: -47.886638,
    },
    {
        nr: 3,
        user: "Pedestrian Crossing ",
        intro: "A long wait",
        about: "Pedestrians often wait very long for the traffic lights to turn red for the cars and assure a safer crossing of the road. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='pedestrian_crossing_g5.jpg' />", 
        lat: -15.789881, 
        lng: -47.890446,
    },
{
        nr: 4,
        user: "Problems of accessibility",
        intro: "Not always easy",
        about: "One of many examples of problems of accessibility in Brasilia. This spot is located near a large bus stop along the W3, making it very difficult for people with disabilaties to move freely in the city. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='tree_walkway_g5.jpg'>", 
        lat:  -15.7852965, 
        lng: -47.8879743,
    },
{
        nr: 5,
        user: "Safety in Public Transport",
        intro: "Improving step by step",
        about: "The city's government is however aware of this problem and is working on solutions to make public transport safer, espacially for women. The metro has a wagon which is designated for woman only. They have their one waiting area which is separated from the rest of the platform. The long distances in between bus stops can mean that some people have to walk a very large distance home from the bus stop. Especially at night, this can be dangerous for woman while walking down a badly lit street. After 10 p.m. woman can ask the bus driver to drop them off in between bus stops if this makes their walk home shorter and so safer. These are two examples in which the government tries increasing the safety and so promoting the usage of public transportation. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='metro_women_g5.jpg'>", 
        lat:  -15.8402910, 
        lng: -48.0283089,
    },
 
{
        nr: 6,
        user: "Informal Walkways",
        intro: "Mobility leaves its marks",
        about: "Due to the lack or poor placement of sidewalks and bycicle paths, many informal trails can be found throughout the whole city. People use them to cut across large areas where there is no infrastructure for pedestrians and cyclists. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='informal_trail_g5.jpg'>", 
        lat:  -15.7929895, 
        lng: -47.8806653,
    },
{
        nr: 7,
        user: "Escaping the scorching heat",
        intro: "Long waiting time in the sun",
        about: "The lack of shade and irregular bus times in Brasilia, makes waiting for the bus a really hard time. Here you can see people seeking protection under the bus station until their bus arrives. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='bus_shade_g5.jpg'>", 
        lat:  -15.7341696, 
        lng: -47.8974536,
    },
 
{
        nr: 8,
        user: "Problems of bike mobility",
        intro: "Sudden obstacles",
        about: "While cycling along the bike lanes in Brasilia, the outmost of attention is needed. Sudden obstacles such as trash cans, lamp posts or low hanging tree branches are struggles cyclists have to cope with. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='bike_obstacles_g5.jpg'>", 
        lat:  -15.7717177, 
        lng: -47.8747460,
    },
 
{
        nr: 9,
        user: "Problems of bike mobility",
        intro: "Steep gradients",
        about: "Although Brasilia is mainly flat and should be well suited for a structured cycling network, there are a couple of steep ramps which have to be passed along the way to the University. Heavy city bikes have to ridden up at a high speed or the cyclists have to get of their bikes and push them up the slope. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='bike_slope_g5.jpg'>", 
        lat:  -15.7928582, 
        lng: -47.8743782,
    },
{
        nr: 10,
        user: "Problems of bike mobility",
        intro: "Dangerous crossings",
        about: "The cycle path crosses the road in several locations. The busy road is difficult to cross because there are no traffic lights for the fast passing cars. Steep inclines before a road crossing make the situation even more dangerous. Hard braking is required to get the bike to a stand-still before the road. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='bike_road_steep_g5.jpg'>", 
        lat:  -15.7760486, 
        lng: -47.8717225,
    },
 
{
        nr: 11,
        user: "Problems of bike mobility",
        intro: "City bikes",
        about: "The newest mode of public transport are the shared city bikes. They have been introduced to the city´s network in 2021. They have become more and more popular with the population. Locals say that they really like using the bikes but there are often not enough bikes available and they stand infront of empty stations. The enlargement of the network is the next step to help develop cycling in Brasilia. Here you can see how popular the bikes are and that the demand is clearly there. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='bike_station_empty_g5.jpg'>", 
        lat:  -15.7929988, 
        lng: -47.8830290,
    },
{
        nr: 12,
        user: "Problems of bike mobility",
        intro: "Roots",
        about: "Tree roots cracking up the road surface of the bycicle lanes are a major problem. Bumpy and unpleasant rides can quickly become daangerous while overseeing some literal „jumps“. However during our stay in Brasilia, there was a patch of road which was replaced within a week which shows that their is work being done to improve the cycling experience. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='bike_jump_g5.jpg'>", 
        lat:  -15.7714989, 
        lng: -47.8720360,
    },
{
        nr: 13,
        user: "Problems of bike mobility",
        intro: "Road works ahead",
        about: "During our stay in Brasilia the bikelane near to our sleeping accomadation received a new make over. A tree root had worked itself through the tarmac and made cycling unsafe. The city reacted by fixing the area. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='bike_fix_g5.jpg'>", 
        lat:  -15.7825612, 
        lng: -47.8741040,
	},
 {
        nr: 14,
        user: "Rodoviária de Brasília",
        intro: "A busy place",
        about: "People are on their way to catch the next bus or subway in the center of the plano piloto. Depending on the time, this is a hectic place. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='Rodoviaria_g5.jpg' />", 
        lat:  -15.7938352, 
        lng: -47.8835345,
    },
{
        nr: 15,
        user: "Parking spots",
        intro: "Hard to find",
        about: "In this photo you can clearly see how the cars are parked in the center of the plano piloto on the sides of the main streets. A large number of cars can be seen everywhere. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='parkingspot_g5.jpg' />", 
        lat:  -15.7931393, 
        lng: -47.8850888,
    },
{
        nr: 16,
        user: "Road course",
        intro: "Highway to Heaven or Hell?",
        about: "From the TV tower you have a wonderful view of the streets in the center of plano piloto. The cars on the left are driving towards the photo shooting position and the cars on the right are driving in the other direction. Source: own picture, 12.04.2022.",
        weblink: "Weiterführender Link",
        image: "<img src='roadcourse_g5.jpg' />", 
        lat:  -15.790669447558148, 
        lng: -47.892925828070815,
    },
];
