const GRUPPE4 = [
    {
        nr: 1,
        user: "Brasília Shopping",
        about: " Brasília Shopping is one of the newer malls in the capital. It is located in Asa Norte, right next to the hotel quarter. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='brasiliashopping.jpg' />", 
        lat:  -15.78669,
        lng: -47.88898,
    },
    {
        nr: 2,
        user: "Shopping Conjunto Nacional",
        about: "The Conjunto Nacional was opened in 1971 and is the first shopping centre in Brasília. It is located on the Eixo Monumental, right next to the Rodovaria. Like every shopping mall it has a food court, where a lot of people come during their lunchbreaks. The shops vary concerning their price class and appearance. The products vary: clothing, electronics, libraries, service providers, etc. Nearly everything can be bought except for everyday groceries. It’s central location and proximity to the Rodovaria make it a good place for spontaneous purchases. Whereas other shopping centres fulfill more a role as recreational places. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='conjuntonacional.jpeg'>", 
        lat:  -15.79111,
        lng: -47.88318,
    },
    {
        nr: 3,
        user: "Pátio Brasil Shopping",
        about: "The Pátio Brasil shopping centre is located on the northern end of the Asa Sul. It has a big food court, as the majority of the shopping centres in Brasília. The food court is also well visited during the evenings and is a place for people to meet. The shops cater a middle-income class. Another noticeable fact is its proximity to the medical district. As usual the shopping centre doesn’t really offer supermarkets for day-to-day grocery shopping. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='patiobrasil.jpeg' />", 
        lat:  -15.79504,
        lng: -47.89196,
    },
    {
        nr: 4,
        user: "Iguatemi Brasília",
        about: "The Iguatemi Brasília shopping centre was inaugurated in 2010 and is located in the northern extension of the Lago Norte peninsula. This part of the city is houses higher-income households, which shows at the Iguatemi Brasília. The shopping centre hosts a variety of exclusive boutiques and specialized food shops. The mall is secured and not accessible by foot. Source: own picture",
        image: "<img style='width:400px' src='iguatemi.jpeg' />", 
        lat:  -15.72077, 
        lng: -47.88592,
    },
    {
        nr: 5,
        user: "CL 107/108 Sul",
        about: "The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. This Comércio Local is part of the Unidade de Vizinhança, that contains the Superquadra Modelo. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL107108sul.jpeg' />", 
        lat:  -15.81532, 
        lng: -47.90271,
    },
    {
        nr: 6,
        user: "CL 306/307 Sul",
        about: " The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. This Comércio Local is one of every second which hosts a supermarket and offers the possibility of everyday grocery shopping in proximity and by foot. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src=' CL306307sul.jpg' />", 
        lat:  -15.81175, 
        lng: -47.90161,
    },
    {
        nr: 7,
        user: "CL 308/309 Sul",
        about: " The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. This Comércio Local shows that there are signs of specialization, hosting a lot of fan shops. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL308309sul.jpeg' />", 
        lat:  -15.81553,
        lng: -47.90674,
    },
    {
        nr: 8,
        user: "CL 109/110 Sul",
        about: " The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. This Comércio Local is an extreme example of specialization hosting mainly lighting stores. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL109110sul.jpeg' />", 
        lat:  -15.81918,
        lng: -47.90812,
    },
    {
        nr: 9,
        user: "Superquadra 308 Sul: Superquadra modelo",
        about: "The Superquadra 308 Sul is known as the Superquadra Modelo, showcasing the ideal and intended layout and look of the Superquadras. We had the chance to visit the Superquadra and talk to a resident. On the picture you can see the pillars that are common to all the buildings in the Superquadras. We met here with Bruno who lives in this Superquadra and told us more about it. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src=' SQ308sul.jpg' />", 
        lat:  -15.81497,
        lng: -47.90506,
    },
    {
        nr: 10,
        user: "Superquadra 210 Norte",
        about: "The Superquadra 210 Norte is an example for how the design and look of the buildings have changed over the years. The original designs are nowhere to be seen. We had the chance to visit the Superquadra and talk to a Gilney. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='Superquadra210norte.jpeg' />", 
        lat:  -15.75591,
        lng: -47.88427,
    },
    {
        nr: 11,
        user: "CL 116/316 Norte",
        about: " The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL116316norte.jpeg' />", 
        lat:  -15.73734,
        lng: -47.89583,
    },
    {
        nr: 12,
        user: "CL 115/116 Norte",
        about: " The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL115116norte.jpeg' />", 
        lat:  -15.74021,
        lng: -47.89371,
    },
    {
        nr: 13,
        user: "CL 314/315 Norte",
        about: "The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL314315norte.jpg' />", 
        lat:  -15.74397,	
        lng: -47.89493,
    },
    {
        nr: 14,
        user: "CL 202 Norte",
        about: "The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL202norte.jpeg' />", 
        lat:  -15.78369,
        lng: -47.87809,
    },
    {
        nr: 15,
        user: "CL 402/403 Norte",
        about: "The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. This Comércio Local hosts the supermarket of the Unidade de Vizinhança. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL402403norte.jpeg' />", 
        lat:  -15.78000,
        lng: -47.87587,
    },
    {
        nr: 16,
        user: "CL 203/204 Norte",
        about: "The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='CL203204norte.jpg' />", 
        lat:  -15.77695,
        lng: -47.87865,
    },
    {
        nr: 17,
        user: "Atacadão",
        about: "This hypermarket is a typical example for grocery shopping in the Plano Piloto. They are mostly located around the outlines of Asa Sul and Asa Norte. People reach it by car to do their weekly shopping. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='atacadao.jpg' />", 
        lat:  -15.73505,
        lng: -47.90514,
    },
    {
        nr: 18,
        user: "Feira da AGE - farmers market",
        about: "Some people use the farmers market to get fresh produce. Here we can see a stand from a farmers market in Asa Norte. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click here. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='farmersmarket.jpg' />", 
        lat:  -15.74101,
        lng: -47.89482,
    },
    {
        nr: 19,
        user: "Feira da Torre de TV",
        about: "On the eixo monumental, a few steps away from the Torre de TV, you can find a market showcasing local arts & crafts, as well as souvenir shops. Once a improvised market has now become consolidated. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='hippiemarket.jpeg' />", 
        lat:  -15.79015, 
        lng: -47.89442,
    },
{
        nr: 20,
        user: "CL 406/407 Norte",
        about: "The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. This Comércio Local has a lot of bars and is popular with students because of its proximity to the University. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='barsSQ406407.jpg' />", 
        lat:  -15.76636,
        lng: -47.87760,
    },
{
        nr: 21,
        user: "Commercial space on the Via W2",
        about: "Not only the Comércio Locais offer commercial space but also buildings along the Via W2 and the Via W3. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='geschaefteW2sul.jpg' />", 
        lat:  -15.81098,
        lng: -47.90337,
    },
{
        nr: 22,
        user: "Commercial space on the Via W2",
        about: "Not only the Comércio Locais offer commercial space but also buildings along the Via W2 and the Via W3. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='geschaefteW2sul.jpeg' />", 
        lat:  -15.79504,
        lng: -47.89196,
    },
{
        nr: 23,
        user: "Banca",
        about: "Every Superquadra still has a Banca (Kiosk). If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='Banca.jpeg' />", 
        lat:  -15.75668,
        lng: -47.88291,
    },
{
        nr: 24,
        user: "Leisure in the Superquadras",
        about: "Every Superquadra has sportcourts and playgrounds. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='spielplatz315norte.jpg' />", 
        lat:  -15.74226,
        lng: -47.89559,
    },
{
        nr: 25,
        user: "Living in the Comércio Locais",
        about: " The original idea of the Comércio Local is to supply the residents of the Unidade de Vizinhança, in which it lies, with all products and services needed on an everyday basis. In some cases, the upper Stories, of the commercial buildings, are inhabited. These apartments are known to be cheaper and often are inhabited by people who work in the businesses of the Comércio Local. If you want to learn more about the Comércio Locais, the Superquadras and everyday life in the Plano Piloto click below. Source: own picture, 24.04.2022.",
        image: "<img style='width:400px' src='wohnenCL314315norte.jpg' />", 
        lat:  -15.74433,
        lng: -47.89466,
    },
];