const GRUPPE2 = [
    {
        nr: 1,
        user: "Parque da Cidade",
        about: "The Parque da Cidade offers extensive green and blue spaces and thus plays an important role in the recreational use of the population. With its 420 ha, the city park offers space for various sports activities, barbecue areas, playgrounds for children, a lake and much more. This makes it a popular meeting place among all age groups but unfortunately not all income groups. Since the park is located in the middle of the Plano Piloto and people coming from the satellite cities barely find their way to the center for leisure time, because there is too much time and money spent on the way to get there. On the other hand, people from the Plano Piloto take advantage of the location as it is both a suitable spot for after-work activities during the week and a place to linger on weekends.",
        image: "<img src='parquedacidade.jpeg' />", 
        lat: -15.80238381232582, 
        lng: -47.91231095558836
    },
    {
        nr: 2,
        user: "Eixo Monumental",
        about: "The monumental axis Eixo Monumental in the Plano Piloto spans a 10 km long open space that stretches between the railway station and the government buildings. The axis integrates different uses, squares and open spaces and combines them as a representative space. These include for example the Jardim Burle Marx below the TV Tower and the concrete platforms at the National Museum and the Cathedral. At the eastern end you will find the Square of the Three Powers. By symbolically representing the three powers - legislative, executive and judicial - Oscar Niemeyer wanted to portray Brazil's democratic attitude. Parts of the approximately 250 m wide green axis are also used for temporary events. There, according to the plan, the extremely large and wide open space was considered an area for parade marches, as the immense distances and tangential motorways meant that it could hardly be used in an everyday sense. Therefore, this open space conveys a rather anarchistic feeling and its homogeneous construction of turf and stone emphasises its intimidating infinity. In our study the interviews conducted with students made clear, that people use public space differently to what it was meant to be. A specific example is playing rugby at the big green area at the Eixo Monumental, the central axis, even though the area was originally not planned for free public use. This shows, that planned as well as not planned appropriation differs from initial plans. One student, who took part in a photointerview also said, that the conservation of the yard could be a lot better and the people, who live nearby, are not very welcoming to citizens from satellite cities. ",
        image: "<img src='rugby.jpg'>", 
        lat: -15.797730817014807, 
        lng: -47.87052670388993,
    },
    {
        nr: 3,
        user: " Parque Águas Claras",
        about: "The park in Águas Claras is a popular place for leisure and free time activities. The study group conducted interviews with visitors at that park. Different to other parks at Plano Piloto was, that the people the group met have only been residents from that specific administrative region (satellite city). It seems that those residents did not have the tendancy to leave their city to spend their free time in green spaces for example in bigger parks in Plano Piloto. Nonetheless, it is important to know, that it is a particular case. Some other interviewees as well as the experts mentioned that Águas Claras is a residential area for middle and upper-middle income people. Though in other administrative regions, people sometimes do not have the opportunity to leave their area to get to green-blue spaces at Plano Piloto due to a lack of time and a poor public transport network. The striking difference to Águas Claras is, that other, low income residential areas do often not have their own parks to use for leisure activities. This might be an indicator as well of the segregation inside Brasília.",
        image: "<img src='aguasclaras.jpg' />", 
        lat:  -15.90896, 
        lng: -47.98766,
    },
{
        nr: 4,
        user: "Prohibited activities at a park",
        about: "The sign at the entrance of a park saying that it is a nature reserve prohibits various activities. This shows that the will to preserve nature is also directly related to the use of the park by its visitors. This is why the assumption, that territorial protection i.e. the protection of nature might have an impact on the use of free spaces during leisure activities might be true. Though it is important to know, that there are many different types of protected areas in Distrito Federal.",
        image: "<img src='prohibition_sign.jpg' />", 
        lat:  -15.836528, 
        lng: -47.866270,
    },
  {
        nr: 5,
        user: "Appropriation of public space",
        about: "At the Morro da Asa Delta park, there was a specific conflict of appropriation. Due to the rich residential area, surrounding the Lago Paranoá, it was also the upper class population who was partially trying to appropriate public space next to their parcels to get direct and private access to the lake. This is not only an illegal action, it also threatens the democratic access to the lake as well as its use during leisure activities for people who are living outside the bordering quarters. Furthermore, it underlines the process and the degree of segregation in Brasília.",
        image: "<img src='asadelta.jpeg' />", 
        lat:   -15.837380, 
        lng: -47.864474,
    },
{
        nr: 6,
        user: " Lago Paranoá - Unequal access to public blue space",
        about: "The Lago Paranoá is the biggest blue space in Brasília. A blue space includes linear water bodies such as rivers as well as shallow waters such as reservoirs and wetlands. In this case, it is an artificially created lake towards which the Plano Piloto faces. It is meant to be accessible to everybody for the use of leisure activities. Though, it is surrounded by a residential area of the upper class, who is partially blocking the access to the lake to non-residents. (For a concrete example click the box of Morro da Asa Delta). On the one hand, this area gets more and more unattractive to people residing somewhere else at Plano Piloto or even in the administrative regions outside Plano Piloto, due to long distances as well as the feeling of not being welcome. On the other hand, this encourages and facilitates the upper class’ opportunity for creating leisure clubs using the access privately.",
        image: "<img src='lago_paranoa.jpg' />", 
        lat: -15.791370, 
        lng: -47.815645,
    },
{
        nr: 7,
        user: " Parque Ecológico dos Jequitibás ",
        about: "The Parque Ecológico dos Jequitibás is located in the satellite city Sobradinho. The majority of the students from Brasília, who took part in our field studies, called this place their home. They also pointed out, that they spend a lot of their free time in this park, who offers a lot of attractive infrastructure with green and blue spaces for leisure activities. Mostly people from Sobradinho use that area, because people with higher income from Plano Piloto are not interested in exploring the green spaces of satellite cities. This aspect creates a problem, because they will never be confronted with the inferior living and working conditions. Unfortunately, satellite cities don´t often contain and preserve inviting green spaces for leisure time. A strong example refering to the lack of park-infrastructure is the satellite city called Ceilandia, in which almost no green or blue spaces are found between concrete areas. One student even said, that the establishment of green and attractive infrastructure is neglected on purpose, so the citizens don´t recover and only focus on lucrative work. In addition, many people from satellite cities with low income don´t have the ressources to reach the pleasant parks in the plano piloto area. They remain almost unaccessable for them.",
        image: "<img src='jequitibas.jpg' />", 
        lat: -15.640917900644647, 
        lng: -47.78875939325434
    },
{
        nr: 8,
        user: "Estação Ecológica de Águas Emendadas",
        about: "The Estação Ecológica de Águas Emendadas is one of the three most important areas for natural protection in Brasília, next to national park and the botanical garden, which stand under high ecological pressure. It covers an area of 10,547 ha and is home to ecosystems of great ecological importance. It forms the junction of the two largest South American river basins, the Amazon and La Plata, which connect in a common source in a 6 km long path. It is also of great importance for the conservation of the landscape and habitats of the Cerrado. Several government agencies and scientific institutions at national and international level conduct research in the station. Due to the construction of residential areas and urban settlements in its vicinity, the anthropogenic pressure on the Águas Emendadas is enormous. In its surroundings there are large cultivated areas whose agricultural techniques attack the environment, expose the soil and cause erosion.",
        image: "<img src='aguasemendadas.jpg' />", 
        lat: -15.553008447642128, 
        lng: -47.60287349216539,
},
    {
        nr: 9,
        user: " Parque Ecológico do Cortado ",
        about: "The Parque Ecológico do Cortado is a green area located in the satellite city called Taguatinga.  It can be taken as the perfect example for superficial sustainability in ecological parks in Brasília. In the course of an Photointerview, one student of the University of Brasília sent us a picture of a littered waterfall surrounding that shows the lack of maintencance in these areas. Furthermore he mentioned, that the security aspect also needs improvement, since cases of rubbery, assault and abuse happen due to a lack of securities. In addition he told us, as a result of the bad maintainance of these green and blue spaces, tropical diseases can develop and spread more easily. An example referring to this is the dengue mosquito, which creates its habitat in stagnant water areas with tropical climate conditions and spreads dengue fever, which is already a problem in Brasília.",
        image: "<img src='trash.jpg' />", 
        lat:   -15.812444600067673, 
        lng:     -48.07833518588563,
    },

    {
        nr: 10,
        user: "Parque Nacional de Brasília",
        about: " The national park is located in the northwest of the Distrito Federal. The main objective of the park is to preserve an important section of the Cerrado biome and the water quality of the Santa Maria reservoir, which provides 25 percent of Brasília's drinking water supply, and the Torto and Bananal rivers, which contribute to Lago Paranoá. For the local population, it is a popular place for recreation. The main attractions are the natural pools fed by water from the headwaters in the park. The park charges an entrance fee and is not as centrally located as, for example, Parque da Cidade. Therefore, most people visit it mainly on weekends when there is enough time. Because of the cost, not everyone can afford to visit the park. In addition, the park also clearly feels the effects of human activity. Industrial, commercial and residential areas, which are not compatible with the purpose of the park cause considerable damage. One of the most serious problems is the landfill in the bordering area.",
        image: "<img src=' parque_nacional.jpg' />", 
        lat: -15.738213141707815,
        lng: -47.926504745870304,
    },
    {
	    nr: 11,
        user: " Jardim Botânico",
        about: " The Estação Ecológica Jardim Botânico de Brasília is an important area for the conservation and study of the Cerrado. In 1991, the Ecological Station of the Botanical Garden was expanded by about 3,800 ha, making it the largest botanical garden in the world located in a savanna (total 4,431.83 ha). The area contains all the different species of Cerrado phytophysiognomies and different animals characteristic of the regional fauna. However, only a part of the park is open to the public. Moreover, the park is difficult for most people to reach without a car. Therefore, it is seen by many residents as a park built specifically for the neighborhood of the Jardim Botânico.",
        image: "<img src=' jardim_botânico.jpg' />", 
        lat: -15.873968712380686, 
        lng: -47.83431465435166,
    },
{
 	  nr: 12,
        user: " Área de Proteção Ambiental (APA) do Planalto Central",
        about: " The APA covers about 505,000 hectares and represents 65 percent of the southern part of DF, with an additional share in Goiás. APA belongs to the first level of protected areas (weak protection) and has no clear boundaries. It was created 20 years ago to regulate water resources and land allocation/conservation. But unfortunately, there are many problems in the APA area. First, there is the illegal construction in the hinterland but also in particularly sought-after protected spaces near the Lago Paranoá, from where one can enjoy a beautiful view of the lake. Illegal construction first causes illegal clearing. This often causes wildfires, which cannot be extinguished easily or at all. In addition, the inhabitants of the houses that have existed for more than 5 years are allowed to stay there without having received a notification from the administration. One of the biggest challenges is the water supply. Brasília is now the third largest city in Brazil. The development is proceeding rapidly. But there is not enough water for the number of residents. Therefore, some water has to be imported from Goiás. In addition, there is not a sewage system everywhere. Therefore, people drill illegal wells for water and illegal holes for feces. As a result, the natural water system is polluted and regenerates slowly. There are also conflicts with recreational uses. For example, illegal houses are built on established mountain bike trails. Other areas are only open to researchers. This is not respected by many people and they still spend their free time there, treating nature carelessly and leaving trash behind. APA receives little support from the government. Environmental protection has the lowest priority. Thus, APA also has few funding options. There is almost nothing left for the education of the inhabitants, although this would be the most important contribution for a positive change.",
        image: "<img src=' illegal_construction_APA.jpg' />", 
        lat: -15.602935332003089, 
        lng: -47.89024563575431,
    },


]
