const GRUPPE4 = [
    {
        nr: 1,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -15.80896, 
        lng: -47.94766,
    },
    {
        nr: 2,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -15.82896, 
        lng: -47.94766,
    },
    {
        nr: 3,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -15.83896, 
        lng: -47.94766,
    },
    {
        nr: 4,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -15.84896, 
        lng: -47.94766,
    },
    {
        nr: 5,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -15.85896, 
        lng: -47.94766,
    },

];