const GRUPPE4 = [
    {
        nr: 1,
        user: "Brasília Shopping",
        Adresse: "",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "https://brasiliashopping.com.br/,",
        image: "<img src='brasiliashopping.jpeg' />", 
        lat:  -15.78669,
        lng: -47.88898,
    },
    {
        nr: 2,
        user: "Shopping Conjunto Nacional",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "The Conjunto Nacional was opened in 1971 and is the first shopping centre in Brasília. It is located on the eixo monumental, right next to the rodovaria. Like every shopping mall it has a food court, where a lot of people come during their lunchbreaks. The shops vary concerning their price class and appearance. The products vary: clothing, electronics, libraries, service providers, etc. Nearly everything can be bought except for everyday groceries. It’s central location and proximity to the rodovaria make it a good place for spontaneous purchases. Whereas other shopping centres fulfill more a role as recreational places.",
        weblink: "http://www.conjuntonacional.com.br/",
        image: "<img src='conjuntonacional.jpeg'>", 
        lat:  -15.79111,
        lng: -47.88318,
    },
    {
        nr: 3,
        user: "Pátio Brasil Shopping",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "The Pátio Brasil shopping centre is located on the northern end of the asa sul. It has a big food court, as the majority of the shopping centres in Brasília. The food court is also well visited during the evenings and is a place for people to meet. The shops cater a middle-income class. Another noticeable fact is its proximity to the medical district. As usual the shopping centre doesn’t really offer supermarkets for day to day grocery shopping.",
        weblink: "https://www.patiobrasil.com.br/",
        image: "<img src='patiobrasil.jpeg' />", 
        lat:  -15.79504,
        lng: -47.89196,
    },
    {
        nr: 4,
        user: "Iguatemi Brasília",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "The Iguatemi Brasília shopping centre was inaugurated in 2010 and is located in the northern extension of the lago norte peninsula. This part of the city is houses higher-income households, which shows at the Iguatemi Brasília. The shopping centre hosts a variety of exclusive boutiques and specialized food shops. The mall is secured and not accessible by foot.",
        weblink: "https://www.iguatemibrasilia.com.br/",
        image: "<img src='iguatemi.jpeg' />", 
        lat:  -15.72077, 
        lng: -47.88592,
    },
    {
        nr: 5,
        user: "CL 107/108 Sul",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "The original idea of the commercio local is to supply the residents of the unidade the vizinhança, in which it lies, with all products and services needed on an everyday basis. This commercio local is part of the unidade de vizinhança that contains the superquadra modelo. If you want to learn more about the commercio locals, the superquadras and everyday life in the plano piloto click here. ",
        weblink: "",
        image: "<img src='CL107108sul.jpeg' />", 
        lat:  -15.81532, 
        lng: -47.90271,
    },
    {
        nr: 6,
        user: "CL 306/307 Sul",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "The original idea of the commercio local is to supply the residents of the unidade the vizinhança, in which it lies, with all products and services needed on an everyday basis. This commercio local is one of every second which hosts a supermarket and offers the possibility of everyday grocery shopping in proximity and by foot. If you want to learn more about the commercio locals, the superquadras and everyday life in the plano piloto click here.",
        weblink: "",
        image: "<img src='CL306307sul.jpeg' />", 
        lat:  -15.81175, 
        lng: -47.90161,
    },
    {
        nr: 7,
        user: "CL 308/309 Sul",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "The original idea of the commercio local is to supply the residents of the unidade the vizinhança, in which it lies, with all products and services needed on an everyday basis. This commercio local shows that there are signs of specialization, hosting a lot of fan shops. If you want to learn more about the commercio locals, the superquadras and everyday life in the plano piloto click here.",
        image: "<img src='CL308309sul.jpeg' />", 
        lat:  -15.81553,
        lng: -47.90674,
    },
    {
        nr: 8,
        user: "CL 109/110 Sul",
        Adresse: "Adresse",
        intro: "Mainly Lighing stores, few electronics stores, Pet Supplies Shop and Housewares Store",
        about: "The original idea of the commercio local is to supply the residents of the unidade the vizinhança, in which it lies, with all products and services needed on an everyday basis. This commercio local is an extreme example of specialization hosting mainly lighting stores. If you want to learn more about the commercio locals, the superquadras and everyday life in the plano piloto click here.",
        image: "<img src='CL109110sul.jpeg' />", 
        lat:  -15.81918,
        lng: -47.90812,
    },
    {
        nr: 9,
        user: "Superquadra 308 Sul: Superquadra modelo",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "The superquadra 308 Sul is known as the superquadra modelo, showcasing the ideal and intended layout and look of the superquadras. We had the chance to visit the superquadra and talk to a resident. If you want to learn more about the commercio locals, the superquadras and everyday life in the plano piloto click here.",
        weblink: "",
        image: "<img src='patiobrasil.jpeg' />", 
        lat:  -15.79504,
        lng: -47.89196,
    },
    {
        nr: 10,
        user: "Superquadra 210 Norte",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "The Superquadra 210 Norte is an example for how the design an look of the buildings have changed over the years. The original designs are nowhere to be seen. We had the chance to visit the superquadra and talk to a resident. If you want to learn more about the commercio locals, the superquadras and everyday life in the plano piloto click here.",
        weblink: "",
        image: "<img src='patiobrasil.jpeg' />", 
        lat:  -15.79504,
        lng: -47.89196,
    },
    {
        nr: 11,
        user: "CL 116/316 Norte",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "",
        weblink: "",
        image: "<img src='CL116316norte.jpeg' />", 
        lat:  -15.73734,
        lng: -47.89583,
    },
    {
        nr: 12,
        user: "CL 115/116 Norte",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "",
        image: "<img src='CL115116norte.jpeg' />", 
        lat:  -15.74021,
        lng: -47.89371,
    },
    {
        nr: 13,
        user: "CL 314/315 Norte",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "",
        image: "<img src='CL314315norte.jpeg' />", 
        lat:  -15.74397,	
        lng: -47.89493,
    },
    {
        nr: 14,
        user: "CL 202 Norte",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "",
        image: "<img src='CL202norte.jpeg' />", 
        lat:  -15.78369,
        lng: -47.87809,
    },
    {
        nr: 15,
        user: "CL 402/403 Norte",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "",
        image: "<img src='CL402403norte.jpeg' />", 
        lat:  -15.78000,
        lng: -47.87587,
    },
    {
        nr: 16,
        user: "CL 203/204 Norte",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "",
        image: "<img src='CL203204norte.jpeg' />", 
        lat:  -15.77695,
        lng: -47.87865,
    },
    {
        nr: 17,
        user: "Atacadao",
        Adresse: "Adresse",
        intro: "Hypermarket",
        about: "This hypermarket is a typical example for grocery shopping in the plano piloto. They are mostly located around the outlines of asa sul and asa Norte. People reach it by car to do their weekly shopping.",
        weblink: "",
        image: "<img src='atacadao.jpeg' />", 
        lat:  -15.73505,
        lng: -47.90514,
    },
    {
        nr: 18,
        user: "Feira da AGE - farmersmarket",
        Adresse: "Adresse",
        intro: "Farmersmarket",
        about: "Beschreibung",
        weblink: "",
        image: "<img src='feira.jpeg' />", 
        lat:  -15.74101,
        lng: -47.89482,
    },
    {
        nr: 19,
        user: "Feira da Torre de TV",
        Adresse: "Adresse",
        intro: "Hippiemarket / furniture / Arts & Crafts",
        about: "On the eixo monumental, a few steps away from the Torre de TV, you can find a market showcasing local arts & crafts, as well as souvenir shops. Once a improvised market has now become consolidated. ",
        weblink: "",
        image: "<img src='hippiemarket.jpeg' />", 
        lat:  -15.79015, 
        lng: -47.89442,
    },



];
