const GRUPPE1 = [
    {
        nr: 1,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' height=\'20px\' width=\'20px\'>", 
        lat:  -15.80896, 
        lng: -47.94766,
    },
    {
        nr: 1,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg'>", 
        lat:  -15.75896, 
        lng: -47.82766,
    },
    {
        nr: 1,
        user: "TITEL",
        Adresse: "Adresse",
        intro: "Untertitel",
        about: "Beschreibung",
        weblink: "Weiterführender Link",
        image: "<img src='church.jpeg' />", 
        lat:  -15.90896, 
        lng: -47.98766,
    },

    {
        nr: 5,
        user: "Vila Planalto: A unique neighbourhood in Brasília",
        about: "Different surfaces, different wall coverings, unequal levels of safety equipment: the architectural design is very different from the rest of the well-planned city of Brasília. At the same time, this also emphasises the diversity of Vila Planalto's inhabitants.",
        image: "<img src='vila1.jpg' />", 
        lat: -15.790410, 
        lng: -47.853551,
    },
    {
        nr: 6,
        user: "Sports in Vila Planalto",
        about: " A perfectly maintained football pitch indicates the higher-class society in Vila Planalto. According to the motto ’Sports for Development’, sport can also have a positive and integrating effect on the whole community.",
        image: "<img src='vila2.jpg' />", 
        lat: -15.792898, 
        lng: -47.849874,
    },
        {
        nr: 7,
        user: "Everyday life in Vila Planalto",
        about: " Rubbish and its unpleasant odour are also part of everyday life in Vila Planalto. This is evident on the streets as well as in other public places. Also, it is interesting to pay attention to the surface of the streets, as this could indicate the wealth of the people living in the area. In Vila Planalto there are a high variety of coverings which represent the diversity within the neighbourhood.",
        image: "<img src='vila3.jpg' />", 
        lat: -15.791737, 
        lng: -47.852303,
        },
        {
        nr: 8,
        user: "Culture and Urbanity",
        about: " A vibrant cultural life is often considered an important factor in the sense of urbanity. Culture in this context is understood in a broader sense. The presence of subcultural activities is also part of this definition. Graffiti and this book exchange in a bus shelter can be seen as indicators of a growing interest in cultural actions.",
        image: "<img src='vila4.jpg' />", 
        lat: -15.794436, 
        lng: -47.853869,
        },
        {
        nr: 9,
        user: "Historic context of Vila Planalto",
        about: "Vila Planalto was founded in 1957 as a camp for workers involved in the construction of Brasília. After the completion of the Plano Piloto, the workers were supposed to move elsewhere, but due to widespread protests they were allowed to stay. Today, not only workers but also members of the upper class live in the neighbourhood, a fact which is made apparent by the presence of more luxurious houses and facade designs.",
        image: "<img src='vila5.jpg' />", 
        lat: -15.792383, 
        lng: -47.854601,
        },
        {
        nr: 10,
        user: "Individualism and its consequences",
        about: " While very strict regulations prevail in the listed Plano Piloto, the configuration of Vila Planalto appears much more liberal. Depending on the house owner, different facades and sidewalks reveal a growing interest for individual designs. This is enabled by reduced administrative influence on construction activities.",
        image: "<img src='vila6.jpg' />", 
        lat: -15.790927, 
        lng: -47.853660,
        },
        {
        nr: 11,
        user: "Designed house facades and security installations",
        about: " The possibility of customizing your own home has led to some buildings reaching ‘artistic’ proportions. At the same time, extensive security measures can also be observed.",
        image: "<img src='vila7.jpg' />", 
        lat: -15.794594, 
        lng: -47.851824,
        },
        {
        nr: 12,
        user: "Climate influences the daily life",
        about: " The fitness equipment installed in the central square indexes the possible municipal influence on the area. However, the observations show that due to the high temperatures and lack of shade, they were not used regularly, at least during the observation periods.",
        image: "<img src='vila8.jpg' />", 
        lat: -15.794081, 
        lng: -47.850277,
        },
        {
        nr: 13,
        user: "Urban atmosphere in Vila Planalto",
        about: " The Western European image of urbanity, the urban meilleu, and the public can be expanded by a visit to Brasília. The results of the walk show classic elements such as green spaces and retail as indicators of urbanity. However, they also emphasize the feeling of life behind it, which can be partially perceived in Vila Planalto.",
        image: "<img src='vila9.jpg' />", 
        lat: -15.791483, 
        lng: -47.849754,
        },
        {
        nr: 14,
        user: "Gastronomy as factor for urbanity",
        about: " Consumption opportunities are almost always mentioned in the context of the urbanity debate. In particular the side of Vila Planalto facing the ministries has developed as a gastronomic hotspot where many employees from Plano Piloto spend their lunch break. There are now over 40 different restaurants serving a variety of cuisines.",
        image: "<img src='vila10.jpg' />", 
        lat: -15.790281, 
        lng: -47.854677,
        },
        {
        nr: 15,
        user: "Graffiti and subcultural activities",
        about: "Several walls in Vila Planalto are full of graffiti. Grafittiis considered an expression of urban life, youthfulness, and subculture, but also a political protest and/or artistic act. A distinct graffiti landscape therefore suggests an active political scene as well as the presence of subcultural activities.",
        image: "<img src='vila11.jpg' />", 
        lat: -15.791732, 
        lng: -47.852637,
        },
        {
        nr: 16,
        user: "Religious institutions as part of community life",
        about: " A strong community life includes, among other things, religious associations. These are also present in various forms in Vila Planalto.",
        image: "<img src='vila12.jpg' />", 
        lat: -15.795175, 
        lng: -47.851249,
        },
        {
        nr: 17,
        user: "Green spaces and quality of life",
        about: " Green in the city is repeatedly described as a component of quality of life and urbanity. In Vila Planalto, various green spaces can be found, but they are in less attractive places and therefore hardly used. An exception are the green outdoor areas of the restaurants in the south of the neighbourhood.",
        image: "<img src='vila13.jpg' />", 
        lat: -15.791520, 
        lng: -47.853356,
        },
        
];

